//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_9DAB36_LABORATORIOEntities : DbContext
    {
        public DB_9DAB36_LABORATORIOEntities()
            : base("name=DB_9DAB36_LABORATORIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COMUNAS> COMUNAS { get; set; }
        public virtual DbSet<CONTACTOS> CONTACTOS { get; set; }
        public virtual DbSet<DATOS_CLIENTES> DATOS_CLIENTES { get; set; }
        public virtual DbSet<DETALLES_EVENTOS> DETALLES_EVENTOS { get; set; }
        public virtual DbSet<DIRECCIONES> DIRECCIONES { get; set; }
        public virtual DbSet<EQUIPOS_INSTALADOS> EQUIPOS_INSTALADOS { get; set; }
        public virtual DbSet<ESTADOS_EVENTOS> ESTADOS_EVENTOS { get; set; }
        public virtual DbSet<EVENTOS> EVENTOS { get; set; }
        public virtual DbSet<HISTORIAL_HORARIOS_UBICACION> HISTORIAL_HORARIOS_UBICACION { get; set; }
        public virtual DbSet<HISTORIAL_USUARIOS> HISTORIAL_USUARIOS { get; set; }
        public virtual DbSet<HORARIOS_UBICACIONES> HORARIOS_UBICACIONES { get; set; }
        public virtual DbSet<MAQUINAS> MAQUINAS { get; set; }
        public virtual DbSet<MARCAS> MARCAS { get; set; }
        public virtual DbSet<MODELOS> MODELOS { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<REGIONES> REGIONES { get; set; }
        public virtual DbSet<RUTAS> RUTAS { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<TIPOS_EVENTOS> TIPOS_EVENTOS { get; set; }
        public virtual DbSet<TIPOS_USUARIOS> TIPOS_USUARIOS { get; set; }
        public virtual DbSet<UBICACIONES> UBICACIONES { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    
        public virtual ObjectResult<Carga_Grilla_Listado_Rutas_Tecnicos_Result> Carga_Grilla_Listado_Rutas_Tecnicos(Nullable<int> id_tecnico)
        {
            var id_tecnicoParameter = id_tecnico.HasValue ?
                new ObjectParameter("id_tecnico", id_tecnico) :
                new ObjectParameter("id_tecnico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Carga_Grilla_Listado_Rutas_Tecnicos_Result>("Carga_Grilla_Listado_Rutas_Tecnicos", id_tecnicoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<Sp_Carga_Combo_Box_Result> Sp_Carga_Combo_Box(Nullable<int> flag, Nullable<int> ddlFlag)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            var ddlFlagParameter = ddlFlag.HasValue ?
                new ObjectParameter("ddlFlag", ddlFlag) :
                new ObjectParameter("ddlFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Carga_Combo_Box_Result>("Sp_Carga_Combo_Box", flagParameter, ddlFlagParameter);
        }
    
        public virtual ObjectResult<Sp_Carga_Grilla_Detalles_Eventos_Result> Sp_Carga_Grilla_Detalles_Eventos(Nullable<int> id_evento)
        {
            var id_eventoParameter = id_evento.HasValue ?
                new ObjectParameter("id_evento", id_evento) :
                new ObjectParameter("id_evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Carga_Grilla_Detalles_Eventos_Result>("Sp_Carga_Grilla_Detalles_Eventos", id_eventoParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int Sp_Registro_Cierra_Evento(Nullable<int> id_evento, string detalle_evento, Nullable<int> id_user)
        {
            var id_eventoParameter = id_evento.HasValue ?
                new ObjectParameter("id_evento", id_evento) :
                new ObjectParameter("id_evento", typeof(int));
    
            var detalle_eventoParameter = detalle_evento != null ?
                new ObjectParameter("detalle_evento", detalle_evento) :
                new ObjectParameter("detalle_evento", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Cierra_Evento", id_eventoParameter, detalle_eventoParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Cliente(Nullable<int> cliente_rut, string cliente_dv, string cliente_nombre, string cliente_paterno, string cliente_materno, Nullable<System.DateTime> cliente_nacimiento, Nullable<int> id_user, string datos_cliente_celular, string datos_cliente_fono, string datos_cliente_email)
        {
            var cliente_rutParameter = cliente_rut.HasValue ?
                new ObjectParameter("cliente_rut", cliente_rut) :
                new ObjectParameter("cliente_rut", typeof(int));
    
            var cliente_dvParameter = cliente_dv != null ?
                new ObjectParameter("cliente_dv", cliente_dv) :
                new ObjectParameter("cliente_dv", typeof(string));
    
            var cliente_nombreParameter = cliente_nombre != null ?
                new ObjectParameter("cliente_nombre", cliente_nombre) :
                new ObjectParameter("cliente_nombre", typeof(string));
    
            var cliente_paternoParameter = cliente_paterno != null ?
                new ObjectParameter("cliente_paterno", cliente_paterno) :
                new ObjectParameter("cliente_paterno", typeof(string));
    
            var cliente_maternoParameter = cliente_materno != null ?
                new ObjectParameter("cliente_materno", cliente_materno) :
                new ObjectParameter("cliente_materno", typeof(string));
    
            var cliente_nacimientoParameter = cliente_nacimiento.HasValue ?
                new ObjectParameter("cliente_nacimiento", cliente_nacimiento) :
                new ObjectParameter("cliente_nacimiento", typeof(System.DateTime));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var datos_cliente_celularParameter = datos_cliente_celular != null ?
                new ObjectParameter("datos_cliente_celular", datos_cliente_celular) :
                new ObjectParameter("datos_cliente_celular", typeof(string));
    
            var datos_cliente_fonoParameter = datos_cliente_fono != null ?
                new ObjectParameter("datos_cliente_fono", datos_cliente_fono) :
                new ObjectParameter("datos_cliente_fono", typeof(string));
    
            var datos_cliente_emailParameter = datos_cliente_email != null ?
                new ObjectParameter("datos_cliente_email", datos_cliente_email) :
                new ObjectParameter("datos_cliente_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Cliente", cliente_rutParameter, cliente_dvParameter, cliente_nombreParameter, cliente_paternoParameter, cliente_maternoParameter, cliente_nacimientoParameter, id_userParameter, datos_cliente_celularParameter, datos_cliente_fonoParameter, datos_cliente_emailParameter);
        }
    
        public virtual int Sp_Registro_Contactos(Nullable<int> ubicacion_id, string nombre, string paterno, string materno, string celular, string telefono, string email, Nullable<int> id_user)
        {
            var ubicacion_idParameter = ubicacion_id.HasValue ?
                new ObjectParameter("ubicacion_id", ubicacion_id) :
                new ObjectParameter("ubicacion_id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("materno", materno) :
                new ObjectParameter("materno", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("celular", celular) :
                new ObjectParameter("celular", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Contactos", ubicacion_idParameter, nombreParameter, paternoParameter, maternoParameter, celularParameter, telefonoParameter, emailParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Detalle_Eventos(Nullable<int> id_evento, string detalle_evento, Nullable<int> id_user)
        {
            var id_eventoParameter = id_evento.HasValue ?
                new ObjectParameter("id_evento", id_evento) :
                new ObjectParameter("id_evento", typeof(int));
    
            var detalle_eventoParameter = detalle_evento != null ?
                new ObjectParameter("detalle_evento", detalle_evento) :
                new ObjectParameter("detalle_evento", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Detalle_Eventos", id_eventoParameter, detalle_eventoParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Direccion(Nullable<int> comuna_id, string direccion_des, Nullable<double> latitud, Nullable<double> longitud, Nullable<int> id_user)
        {
            var comuna_idParameter = comuna_id.HasValue ?
                new ObjectParameter("comuna_id", comuna_id) :
                new ObjectParameter("comuna_id", typeof(int));
    
            var direccion_desParameter = direccion_des != null ?
                new ObjectParameter("direccion_des", direccion_des) :
                new ObjectParameter("direccion_des", typeof(string));
    
            var latitudParameter = latitud.HasValue ?
                new ObjectParameter("latitud", latitud) :
                new ObjectParameter("latitud", typeof(double));
    
            var longitudParameter = longitud.HasValue ?
                new ObjectParameter("longitud", longitud) :
                new ObjectParameter("longitud", typeof(double));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Direccion", comuna_idParameter, direccion_desParameter, latitudParameter, longitudParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Estado_Eventos(string descripcion, Nullable<int> id_user)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Estado_Eventos", descripcionParameter, id_userParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Registro_Eventos(Nullable<int> tipo_evento, Nullable<int> cliente_rut, Nullable<int> maquina_id, string detalle_evento, Nullable<int> id_user, ObjectParameter numero_evento)
        {
            var tipo_eventoParameter = tipo_evento.HasValue ?
                new ObjectParameter("tipo_evento", tipo_evento) :
                new ObjectParameter("tipo_evento", typeof(int));
    
            var cliente_rutParameter = cliente_rut.HasValue ?
                new ObjectParameter("cliente_rut", cliente_rut) :
                new ObjectParameter("cliente_rut", typeof(int));
    
            var maquina_idParameter = maquina_id.HasValue ?
                new ObjectParameter("maquina_id", maquina_id) :
                new ObjectParameter("maquina_id", typeof(int));
    
            var detalle_eventoParameter = detalle_evento != null ?
                new ObjectParameter("detalle_evento", detalle_evento) :
                new ObjectParameter("detalle_evento", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Registro_Eventos", tipo_eventoParameter, cliente_rutParameter, maquina_idParameter, detalle_eventoParameter, id_userParameter, numero_evento);
        }
    
        public virtual int Sp_Registro_Marcas_Equipos(string descripcion, Nullable<int> id_user)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Marcas_Equipos", descripcionParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Modelos_Equipos(string descripcion, Nullable<int> marca_id, Nullable<int> id_user)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var marca_idParameter = marca_id.HasValue ?
                new ObjectParameter("marca_id", marca_id) :
                new ObjectParameter("marca_id", typeof(int));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Modelos_Equipos", descripcionParameter, marca_idParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Ruta_Tecnico(Nullable<int> evento_id, Nullable<int> tecnico_id, Nullable<int> id_user)
        {
            var evento_idParameter = evento_id.HasValue ?
                new ObjectParameter("evento_id", evento_id) :
                new ObjectParameter("evento_id", typeof(int));
    
            var tecnico_idParameter = tecnico_id.HasValue ?
                new ObjectParameter("tecnico_id", tecnico_id) :
                new ObjectParameter("tecnico_id", typeof(int));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Ruta_Tecnico", evento_idParameter, tecnico_idParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Tipos_Usuarios(string descripcion, Nullable<int> id_user)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Tipos_Usuarios", descripcionParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Usuarios(Nullable<int> rut, string dv, string username, string password, string nombre, string paterno, string materno, Nullable<System.DateTime> nacimiento, Nullable<int> id_user, Nullable<int> tipo_usuario_id)
        {
            var rutParameter = rut.HasValue ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(int));
    
            var dvParameter = dv != null ?
                new ObjectParameter("dv", dv) :
                new ObjectParameter("dv", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("materno", materno) :
                new ObjectParameter("materno", typeof(string));
    
            var nacimientoParameter = nacimiento.HasValue ?
                new ObjectParameter("nacimiento", nacimiento) :
                new ObjectParameter("nacimiento", typeof(System.DateTime));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var tipo_usuario_idParameter = tipo_usuario_id.HasValue ?
                new ObjectParameter("tipo_usuario_id", tipo_usuario_id) :
                new ObjectParameter("tipo_usuario_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Usuarios", rutParameter, dvParameter, usernameParameter, passwordParameter, nombreParameter, paternoParameter, maternoParameter, nacimientoParameter, id_userParameter, tipo_usuario_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<CargaGridListarUsuarios_Result> CargaGridListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CargaGridListarUsuarios_Result>("CargaGridListarUsuarios");
        }
    
        public virtual ObjectResult<Sp_Busca_Cliente_Result> Sp_Busca_Cliente(Nullable<int> rut)
        {
            var rutParameter = rut.HasValue ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Busca_Cliente_Result>("Sp_Busca_Cliente", rutParameter);
        }
    
        public virtual int Sp_Cambia_Clave_Usuarios(Nullable<int> rut, string pw, Nullable<int> id_user)
        {
            var rutParameter = rut.HasValue ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(int));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Cambia_Clave_Usuarios", rutParameter, pwParameter, id_userParameter);
        }
    
        public virtual ObjectResult<Sp_Carga_Grilla_Horarios_Result> Sp_Carga_Grilla_Horarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Carga_Grilla_Horarios_Result>("Sp_Carga_Grilla_Horarios");
        }
    
        public virtual ObjectResult<Sp_Carga_Grilla_Listado_Tipos_Usuarios_Result> Sp_Carga_Grilla_Listado_Tipos_Usuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Carga_Grilla_Listado_Tipos_Usuarios_Result>("Sp_Carga_Grilla_Listado_Tipos_Usuarios");
        }
    
        public virtual ObjectResult<Sp_Carga_Grilla_Ubicaciones_Result> Sp_Carga_Grilla_Ubicaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Carga_Grilla_Ubicaciones_Result>("Sp_Carga_Grilla_Ubicaciones");
        }
    
        public virtual ObjectResult<Sp_Envia_Lat_Lng_App_Result> Sp_Envia_Lat_Lng_App(Nullable<int> usuario_rut)
        {
            var usuario_rutParameter = usuario_rut.HasValue ?
                new ObjectParameter("usuario_rut", usuario_rut) :
                new ObjectParameter("usuario_rut", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Envia_Lat_Lng_App_Result>("Sp_Envia_Lat_Lng_App", usuario_rutParameter);
        }
    
        public virtual ObjectResult<Sp_Lista_Eventos_Estado_Result> Sp_Lista_Eventos_Estado(Nullable<int> id_evento)
        {
            var id_eventoParameter = id_evento.HasValue ?
                new ObjectParameter("id_evento", id_evento) :
                new ObjectParameter("id_evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Lista_Eventos_Estado_Result>("Sp_Lista_Eventos_Estado", id_eventoParameter);
        }
    
        public virtual ObjectResult<Sp_Obtiene_Usuarios_Result> Sp_Obtiene_Usuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Obtiene_Usuarios_Result>("Sp_Obtiene_Usuarios");
        }
    
        public virtual int Sp_Registro_Agrega_Dato_Cliete(Nullable<int> rut_cliente, string datos_cliente_celular, string datos_cliente_fono, string datos_cliente_email, Nullable<int> id_user)
        {
            var rut_clienteParameter = rut_cliente.HasValue ?
                new ObjectParameter("rut_cliente", rut_cliente) :
                new ObjectParameter("rut_cliente", typeof(int));
    
            var datos_cliente_celularParameter = datos_cliente_celular != null ?
                new ObjectParameter("datos_cliente_celular", datos_cliente_celular) :
                new ObjectParameter("datos_cliente_celular", typeof(string));
    
            var datos_cliente_fonoParameter = datos_cliente_fono != null ?
                new ObjectParameter("datos_cliente_fono", datos_cliente_fono) :
                new ObjectParameter("datos_cliente_fono", typeof(string));
    
            var datos_cliente_emailParameter = datos_cliente_email != null ?
                new ObjectParameter("datos_cliente_email", datos_cliente_email) :
                new ObjectParameter("datos_cliente_email", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Agrega_Dato_Cliete", rut_clienteParameter, datos_cliente_celularParameter, datos_cliente_fonoParameter, datos_cliente_emailParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Horarios_Ubicaciones(Nullable<System.TimeSpan> hora_apertura, Nullable<System.TimeSpan> hora_cierre, Nullable<int> id_user)
        {
            var hora_aperturaParameter = hora_apertura.HasValue ?
                new ObjectParameter("hora_apertura", hora_apertura) :
                new ObjectParameter("hora_apertura", typeof(System.TimeSpan));
    
            var hora_cierreParameter = hora_cierre.HasValue ?
                new ObjectParameter("hora_cierre", hora_cierre) :
                new ObjectParameter("hora_cierre", typeof(System.TimeSpan));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Horarios_Ubicaciones", hora_aperturaParameter, hora_cierreParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Instalacion_Maquina(Nullable<int> ubicacion_id, Nullable<int> maquina_id, string descripcion, Nullable<int> id_user)
        {
            var ubicacion_idParameter = ubicacion_id.HasValue ?
                new ObjectParameter("ubicacion_id", ubicacion_id) :
                new ObjectParameter("ubicacion_id", typeof(int));
    
            var maquina_idParameter = maquina_id.HasValue ?
                new ObjectParameter("maquina_id", maquina_id) :
                new ObjectParameter("maquina_id", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Instalacion_Maquina", ubicacion_idParameter, maquina_idParameter, descripcionParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Maquinas(string maquina_serie, Nullable<int> modelo_id, Nullable<System.DateTime> maquina_FechaFabri, Nullable<int> id_user)
        {
            var maquina_serieParameter = maquina_serie != null ?
                new ObjectParameter("maquina_serie", maquina_serie) :
                new ObjectParameter("maquina_serie", typeof(string));
    
            var modelo_idParameter = modelo_id.HasValue ?
                new ObjectParameter("modelo_id", modelo_id) :
                new ObjectParameter("modelo_id", typeof(int));
    
            var maquina_FechaFabriParameter = maquina_FechaFabri.HasValue ?
                new ObjectParameter("maquina_FechaFabri", maquina_FechaFabri) :
                new ObjectParameter("maquina_FechaFabri", typeof(System.DateTime));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Maquinas", maquina_serieParameter, modelo_idParameter, maquina_FechaFabriParameter, id_userParameter);
        }
    
        public virtual int Sp_Registro_Ubicacion(Nullable<int> direccion_id, string ubicacion_descripcion, Nullable<int> id_horario, Nullable<int> id_user)
        {
            var direccion_idParameter = direccion_id.HasValue ?
                new ObjectParameter("direccion_id", direccion_id) :
                new ObjectParameter("direccion_id", typeof(int));
    
            var ubicacion_descripcionParameter = ubicacion_descripcion != null ?
                new ObjectParameter("ubicacion_descripcion", ubicacion_descripcion) :
                new ObjectParameter("ubicacion_descripcion", typeof(string));
    
            var id_horarioParameter = id_horario.HasValue ?
                new ObjectParameter("id_horario", id_horario) :
                new ObjectParameter("id_horario", typeof(int));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Registro_Ubicacion", direccion_idParameter, ubicacion_descripcionParameter, id_horarioParameter, id_userParameter);
        }
    
        public virtual ObjectResult<getEventos_Result> getEventos(Nullable<int> id_evento)
        {
            var id_eventoParameter = id_evento.HasValue ?
                new ObjectParameter("id_evento", id_evento) :
                new ObjectParameter("id_evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEventos_Result>("getEventos", id_eventoParameter);
        }
    
        public virtual ObjectResult<Sp_Lista_Eventos_Result> Sp_Lista_Eventos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Lista_Eventos_Result>("Sp_Lista_Eventos");
        }
    
        public virtual ObjectResult<getTodosEventos_Result> getTodosEventos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTodosEventos_Result>("getTodosEventos");
        }
    }
}
